name: Deploy web app
on: push

jobs:
    test_code:
      runs-on: ubuntu-latest
      steps:
          - name: Download code
            uses: actions/checkout@v3
          - name: Investigate the environment
            run:
              pwd
              ls -lart